"""made hashed_password nullable and use cookie only

Revision ID: 8882728d357d
Revises: 1a3a0c5b68e8
Create Date: 2026-04-01 03:04:31.621712

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8882728d357d'
down_revision: Union[str, None] = '1a3a0c5b68e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
