"""uuid schema

Revision ID: 891abab656ce
Revises: f32feb2971d7
Create Date: 2026-03-26 18:49:07.874871

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '891abab656ce'
down_revision: Union[str, None] = 'f32feb2971d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
