"""made hashed_password nullable and use cookie only

Revision ID: 90839778ec5c
Revises: 8882728d357d
Create Date: 2026-04-01 03:19:23.449773

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '90839778ec5c'
down_revision: Union[str, None] = '8882728d357d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
